### ISSUE TITLE
Manual Meta descriptions are inaccurate

### ISSUE THREAD

**Issue by deepjyoti30** [deepjyoti30/ytmdl-web-v2#28]
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [ ] Locally
- [x] On the official page

## Browser Details

- Name: Google Chrome
- Version: (If possible)

## Console Log

```console
Put log if you found one in the browsers console window
```

## Description

In the manual metadata page, each heading has a description explaining what that field does. The following have the wrong description:

- Cover image of the song
- Date release of the song

The description set for the above two are `Enter the name of the artist`.

## Expected Behaviour

The descriptions should indicate what that particular field does.

Issue mailed to me by **Danny**
